<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>SolarOptimiser.Persistence</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Eceni.Core.Base" Version="0.1.0" />
		<PackageReference Include="Eceni.Core.Database.MySQL" Version="0.1.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SolarOptimiser.Domain\SolarOptimiser.Domain.csproj" />
	</ItemGroup>

</Project>
